### ISSUE TITLE
json format

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging-base#1]
First working draft

``` json
{
  "blogs":[
    {
      "title": "Name of Blog",
      "feedURL": "domain2.com/feed.xml",
      "type": "[rss/atom]",
      "homeURL": "domain2.com",
      "category": [
        {
          "title": "Research"
        },
        {
          "title": "Journalism"
        }
      ],
      "TTL": "2014-03-12T13:37:27+00:00"
    },
    {
      "title": "Name of Blog",
      "feedURL": "domain2.com/feed.xml",
      "type": "[rss/atom]",
      "homeURL": "domain2.com",
      "category": [
        {
          "title": "Research"
        },
        {
          "title": "Journalism"
        }
        ],
      "TTL": "2014-03-12T13:37:27+00:00"
    }
  ]
}
```

**Comment by pkra** [comment]
The TTL will store the response header caching information and indicates when the feed should be checked again. It should probably be empty in the repo version but we'll have to write it out as the final action.

**Comment by pkra** [comment]
Do we need a local file name? Did we decide whether we have one part that caches feeds locally and another that processes them? I don't remember.

**Comment by scoskey** [comment]
We didn’t decide. Depending on how the caching is implemented, maybe we could have a faster turnaround time if we did it together...

**Comment by pkra** [comment]
I don't see how we could _not_ store them locally. I think we have to use TTL to minimize traffic -- I don't want to go fetch 1000 feeds every few minutes or even hours. Besides that it'll be a few hundred MB it introduces too many points of failures early on (i.e., ways a failed download can crash the script that we didn't think about).

But if we do use TTL, then we'd have no data for those feeds where `TTL > date()`, no?

**Comment by pkra** [comment]
Do we want to log errors (http headers when other than `200` and other failures) or timestamp for last successful download (the filesystem gives us that, I suppose).

**Comment by pkra** [comment]
Current draft:

``` json
{
  "feeds":[
    {
      "url": "domain.com/feed.xml",
      "category": ["Category 1","Category 2"]
    },
    {
      "url": "domain2.com/feed.xml",
      "category": ["Category 2","Category 3"]
    }
  ]
}
```

Rational: 
- get title from feed
- get home URL from feed
- type is not relevant as feedparser can handle both and does not bother us with it (so far anyway)
- ttl: it's proven unreliable information (not many feeds provide correct headers). So not worth tackling right now (fetching is fast enough for now).

**Comment by pkra** [comment]
Edited to simplify -- categories can just be arrays.
