### ISSUE TITLE
Write out dates in UTC [was: Localizing dates]

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging-base#2]
One day, we'll have dates (I know, right?!?). We should localize them on the client.

https://css-tricks.com/localizing-times-in-javascript/

**Comment by scoskey** [comment]
That sounds like a great idea. We had problems with dates before. We may
still have a problem if some feeds are f'd up, but not much we can do about
that!

I guess the best thing to do would be to write the time in the UTC by
default, and then sneak in a document.ready() that combs the site for <span
class="date"> and rewrites each one using Moment.js. Let's just give this
to our js guy... :)

**Comment by pkra** [comment]
> I guess the best thing to do would be to write the time in the UTC by default, and then sneak in a document.ready() that combs the site for <span class="date"> and rewrites each one using Moment.js. Let's just give this to our js guy... :)

Totally on board with that idea.

**Comment by pkra** [comment]
Something like 

``` javascript
var times = document.getElementsByTagName("time");
for (var i=0; i < times.length; i++) { 
  var time = new Date(times[i].getAttribute("datetime"));
  times[i].innerHTML = time.toDateString();
}
```

should be enough.

**Comment by pkra** [comment]
Since JS localizes automatically.

**Comment by pkra** [comment]
We should probably write out the dates in the initial HTML as UTC. Right now they are "server time" which seems non-optimal.

**Comment by pkra** [comment]
Moved the client-side part to https://github.com/mathblogging/mathblogging.org/issues/5.

If you're ok with UTC, then I can change https://github.com/mathblogging/mathblogging-base/blob/develop/pagewriter.js#L31 to `item.date.toUTCString().substring(5, 16)`

**Comment by pkra** [comment]
Client-side part is fixed upstream.
