### ISSUE TITLE
Should we generate HTML instead of markdown?

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging-base#20]
Lo and behold I'm running into the limitations of markdown.

For #16, I would like to insert proper `<time>` elements. But kramdown does not accept many inline HTML elements.

With HTML we can also set classes and handle styling over to CSS.

What do you think?

**Comment by scoskey** [comment]
Future release?

**Comment by pkra** [comment]
I'm actually half-done... you ok with that?

**Comment by scoskey** [comment]
of course, yes!

**Comment by pkra** [comment]
Yay. Thx. This also leads to changes in mathblogging.org. We should discuss that on the next F2F.
