### ISSUE TITLE
Sanity check dates

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging-base#24]
We should sanitize dates that point to the future and make them the current date.

(There's one just now (Nov 2) at http://images.math.cnrs.fr/Le-mecanisme-d-Anticythere.html saying it's published on Nov 5 (listed as Nov 4 on our site see #2).)

**Comment by scoskey** [comment]
Shouldn't we just filter them out? eventually that date would come and then
we would publish them.

On Mon, Nov 2, 2015 at 2:05 PM, Peter Krautzberger <notifications@github.com

**Comment by pkra** [comment]
Yes, we could do that. I'm worried that somebody will misconfigure their server and put everything a year in advance -- then we'll never see the blog appear. It's published and I tend towards having as much content as possible. But I'd rank it 5 out 10 maybe, so I'm ok with following your solution.

**Comment by scoskey** [comment]
No you are right, it is published, so should we. It is hard though because if people future date then they will stay at the top of our site too long. My dream solution would be to change the date to the date we first found it. But that would take a lot of work.

**Comment by pkra** [comment]
Yes, that would be nice but would require us to cache the feeds and would also prevent us from picking up if the feed gets fixed.

**Comment by pkra** [comment]
Or do a lot of extra work to do both ;-)

**Comment by pkra** [comment]
I'm concerned about my original proposal. If we simply use the current date, then the future-dated blog post will continue to be on the top of the page until it's actual publication date is reached. That seems bad to me. So I'm now leaning more towards your "filter it out" approach. I don't want to start identifying blog posts (how? what if they change the date later?) permanently as this seems too database-y. 

If we filter things out, then the posts will appear at a later date but at the top of the page. That seems fair. Unless the blog is so badly configured that we'll never see it, e.g., pre-dates by a year, 10 posts in the feed, 12 per year. But if somebody configures their site so badly are we to fix it? 

We could log out problematic posts and manually alert their authors. I'm guessing it won't be too many of them (e.g., must be self-hosted, really).

What do you think?
