### ISSUE TITLE
[feedFetchTrimmer] Links missing in slimmed feeds

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging-base#43]
This feed's links are lost: https://ncatlab.org/nlab/atom_with_headlines, leading to `null` in the final merged feeds, which is invalid.

**Comment by jcmckeown** [comment]
don't know if this is relevant (nor even why it would be), but when saving the ncatlab feed as xhtml, all the entries elements seem to be on one very long line, whereas (e.g.) https://xianblog.wordpress.com/feed/ is polite enough to put in lots of linebreaks.

**Comment by jcmckeown** [comment]
OK... that's probably not it, but have now also found: the addresses in ncatlab's feeds are embeded as `href="..."` attributes of self-closed `<link>` elements, while wordpress feeds have unattributed link elements enclosing item urls.  Does node-feedparser care about this difference?

**Comment by pkra** [comment]
Thanks for reminding us of the issue. I'll try to take a look on the weekend.

**Comment by pkra** [comment]
Filed upstream at https://github.com/danmactough/node-feedparser/issues/219.

Should be easy to workaround.
