### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by pkra** [mathblogging/mathblogging-base#8]
- lunrjs (GitHub might support it but perhaps not)
- jets.js https://nexts.github.io/Jets.js/

**Comment by pkra** [comment]
[A request on twitter](https://twitter.com/SmithWinthrop/status/699289688155140096) for full text search. The only way I can see this being done is going back to the early days and [Google Custom Search](https://cse.google.com/cse/) (but I'm not even clear if a several-sites search is still available in the ad-driven free version).

**Comment by pkra** [comment]
We made progress on setting up a CSE. We need to generate a list of root urls to make it work

**Comment by pkra** [comment]
Basic setup at http://mathblogging.org/search/ (not filled with many sites yet)

**Comment by pkra** [comment]
the injected table totally needs some matching CSS though...

**Comment by scoskey** [comment]
That is possible with the Look & Feel editor, so we can look into that
whenever.
